[main]
plugins=keyfile
dhcp=internal
dns=default
rc-manager=file
hostname-mode=none
no-auto-default=*
auth-polkit=root-only

[keyfile]
# Strictly exclude USB, loopback, BT and WWAN; manage only the WLAN device.
unmanaged-devices=*,except:interface-name:wlan0
path=/run/NetworkManager/system-connections

[device-chef-wifi]
match-device=interface-name:wlan0
wifi.backend=wpa_supplicant
wifi.scan-rand-mac-address=no

[connection]
wifi.cloned-mac-address=preserve
