#!/usr/bin/env python3
"""Generate font9x15.h for fblog from the X11 misc-fixed 9x15 PCF font.

The misc-fixed fonts are public domain (X Consortium / Unicode.org "fixed"
family). Reads /usr/share/fonts/X11/misc/9x15-ISO8859-1.pcf.gz through
Pillow's PcfFontFile and emits one uint16_t row per scanline per glyph,
MSB = leftmost pixel, for ASCII 0x20..0x7E plus a final "unknown" glyph
(the 0x7F position, drawn as a hollow box) used for every other byte.
Run once and commit the output; the build never needs Pillow.
"""
import gzip, io, sys
from PIL import PcfFontFile

SRC = sys.argv[1] if len(sys.argv) > 1 else '/usr/share/fonts/X11/misc/9x15-ISO8859-1.pcf.gz'
W, H = 9, 15
f = PcfFontFile.PcfFontFile(io.BytesIO(gzip.open(SRC).read()))
out = []
out.append('/* Generated by tools/fblog/mkfont.py from %s (X11 misc-fixed, public domain).' % SRC.split('/')[-1])
out.append(' * Do not edit: 96 glyphs, ASCII 0x20..0x7E then one "unknown" box glyph; each row is a')
out.append(' * uint16_t with bit 15 = leftmost of the %d pixels. */' % W)
out.append('#define FBLOG_FONT_W %d' % W)
out.append('#define FBLOG_FONT_H %d' % H)
out.append('#define FBLOG_FONT_GLYPHS 96')
out.append('static const uint16_t fblog_font[FBLOG_FONT_GLYPHS][FBLOG_FONT_H] = {')
for code in range(0x20, 0x80):
    rows = []
    if code == 0x7F:
        # hollow box for bytes outside 0x20..0x7E
        for y in range(H):
            if y in (1, H - 2):
                bits = ((1 << (W - 1)) - 1) & ~1
            elif 1 < y < H - 2:
                bits = (1 << (W - 2)) | 2
            else:
                bits = 0
            rows.append(bits)
    else:
        g = f.glyph[code]
        img = g[3] if g else None
        assert img is None or img.size == (W, H), (code, img and img.size)
        for y in range(H):
            bits = 0
            for x in range(W):
                if img is not None and img.getpixel((x, y)):
                    bits |= 1 << (W - 1 - x)
            rows.append(bits)
    label = chr(code) if 0x20 <= code < 0x7F else 'unknown'
    if label == '\\': label = 'backslash'
    if label == '*': label = 'asterisk'
    if label == '/': label = 'slash'
    out.append('\t/* %s */ { %s },' % (label, ', '.join('0x%04x' % r for r in rows)))
out.append('};')
open('font9x15.h', 'w').write('\n'.join(out) + '\n')
print('wrote font9x15.h')
